name: update-typescript-docs
inputs:
  docs-input-path:
    required: true
# output:
#   generatedDocs:
#     value: ${{ insert here }}
runs:
  using: "composite"
  steps:
    - run: echo Path ${{ inputs.docs-input-path }}
      shell: bash