name: 'Update Typescript Documentation'
description: 'Pulls the API docs from the Tauri branch and submits a PR to tauri-docs'
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - run: npm install
      working-directory: ${{ github.action_path }}
      shell: bash
    - run: echo "Build finished"
      shell: bash