name: generate-js-docs
inputs:
  tsconfig-filepath:
    description: .tsconfig file used for indicating the root directory.
    required: false 
    default: ".tsconfig"
  entry-points:
    description: File that is used as the entrypoint to being generating docs.
    required: false
    default: "src/index.ts"
outputs:
  output-path:
    description: Where the generated files are stored
runs:
  using: "node12"
  main: "dist/index.js"