name: Congrats
# Adapted from https://github.com/withastro/automation/blob/main/.github/workflows/congratsbot.yml

on:
  workflow_call:
    secrets:
        DISCORD_WEBHOOK:
          description: >
            URL of a Discord webhook. To create one:
              1. Find the channel you want to post congrats in.
              2. Right-click and select “Edit Channel”.
              3. Navigate to “Integrations” > “View Webhooks”.
              4. Click “New Webhook” and copy the URL for your newly created webhook.
          required: true
jobs:
  post-message:
    runs-on: ubuntu-latest
    steps:
      - name: Send message on Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: 'Thanks `${{ github.event.commits[0].author.username }}` for `${{ github.event.commits[0].message }}` in `${{ github.event.repository.name }}` 🎉 \n <${{ github.event.commits[0].url }}>'
