name: test-generate-docs
on: [push]

jobs:
  run-generate-js-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: tauri-apps/tauri
      - uses: tauri-apps/github-actions/generate-js-docs@dev
        with:
          tsconfig-filepath: tooling/api/tsconfig.json
          entry-points: tooling/api/src/index.ts
      - run: tree .