name: test-update-typescript-docs
on:
  push:
  workflow_dispatch:

jobs:
  get-latest-tauri-files:
    runs-on: ubuntu-latest
    steps:
      - uses: tauri-apps/github-actions/update-typescript-docs@dev
        with:
          path: "update-typescript-docs"