name: update-typescript-doc
on:
  workflow_call:
    inputs:
      sourceDir:
        required: true
        type: string
  
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: cp -r ${{ inputs.sourceDir }} docs/
      - run: yarn && yarn build
        working-directory: update-typescript-docs
      - uses: actions/upload-artifact@v2
        with:
          name: js-docs
          path: output
