name: update-typescript-doc
on: [push, workflow_dispatch]
  
jobs:
  prepare-environment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn
  build-docs:
    steps:
      - run: yarn build
