name: update-typescript-doc
on: [push, workflow_dispatch]
  
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: ls
